#! /bin/sh

sxhkd &
feh --bg-fill ~/.wallpaper/wp1.jpg --bg-fill ~/.wallpaper/wp2.png &
compton &

bspc monitor HDMI-1 -n 0 -d 1 2 3 4
bspc monitor eDP-1 -n 1 -d 5 6 7 8

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color #2F2F2F
bspc config active_border_color #bd00ff
bspc config focused_border_color #00b8ff

bspc config -m HDMI-1 top_padding 22
bspc config -m eDP-1 top_padding 0


# KDE windows
bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off layer=above
bspc rule -a yakuake state=floating border=off layer=above
